# Generated by Django 3.2.7 on 2021-10-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameformat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('role_in_team', models.CharField(choices=[('ba', 'ba'), ('bo', 'bo'), ('all', 'all')], default='all', max_length=100)),
                ('matches_played_so_far', models.IntegerField()),
                ('year_of_entry_into_team', models.DateTimeField()),
            ],
            options={
                'ordering': ('matches_played_so_far',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('drone_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='info.gameformat')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(default='', max_length=150)),
                ('no_of_titles', models.IntegerField()),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='info.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.team')),
            ],
            options={
                'ordering': ('-no_of_titles',),
            },
        ),
    ]
