# Generated by Django 3.2.7 on 2021-10-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='drone_category',
            new_name='game_format',
        ),
    ]
