# Generated by Django 3.2.7 on 2021-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_drone_category_team_game_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role_in_team',
            field=models.CharField(choices=[('ba', 'batsman'), ('bo', 'bowler'), ('all', 'allrounder')], default='all', max_length=100),
        ),
    ]
