# Generated by Django 3.2.7 on 2021-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_player_role_in_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role_in_team',
            field=models.CharField(choices=[('batsman', 'batsman'), ('bowler', 'bowler'), ('allrounder', 'allrounder')], default='allrounder', max_length=100),
        ),
    ]
