# Generated by Django 3.2.7 on 2021-10-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_player_role_in_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='Player',
        ),
    ]
