# Generated by Django 3.2.7 on 2021-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_tournament_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches_played_so_far',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year_of_entry_into_team',
        ),
        migrations.AddField(
            model_name='player',
            name='hundreds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
