# Generated by Django 3.2.7 on 2021-12-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_life',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.player')),
                ('instagram_followers', models.IntegerField(default=0)),
                ('facebook_followers', models.IntegerField(default=0)),
                ('cars_owned', models.IntegerField(default=0)),
                ('is_married', models.BooleanField(default=False)),
            ],
            bases=('info.player',),
        ),
    ]
